[project]
name = "mastodon-archiver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pathlib2>=2.3.7 ; python_full_version < '3.4'",
    "requests>=2.31.0",
]
